// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ChequeBookService.Models;

namespace ChequeBookService.Data
{
    public partial class ChequeBookServiceContext : DbContext
    {
        public ChequeBookServiceContext()
        {
        }

        public ChequeBookServiceContext(DbContextOptions<ChequeBookServiceContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AutomateEntity> AutomateEntities { get; set; }
        public virtual DbSet<ChequeBook> ChequeBooks { get; set; }
        public virtual DbSet<ConfigParam> ConfigParams { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AutomateEntity>(entity =>
            {
                entity.Property(e => e.DateRun).HasComment("date of last execution");

                entity.Property(e => e.Entity).HasComment("the entity or subject on which execution took place");

                entity.Property(e => e.EntityCount).HasComment("the count during the execution");

                entity.Property(e => e.RunFlag).HasComment("flag determining if execution has finished");
            });

            modelBuilder.Entity<ConfigParam>(entity =>
            {
                entity.Property(e => e.ConfigKey).IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        #region DbConfig

        protected override void OnConfiguring(DbContextOptionsBuilder builder)
        {
            builder.UseSqlServer(@"Data Source=DESKTOP-AHTKNDP\ITWORKS;Initial Catalog=DAutomate;User ID=sa;Password=excalibur@33;TrustServerCertificate=True");
        }

        #endregion

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}