// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ChequeBookService.Models
{
    [Table("AutomateEntity")]
    public partial class AutomateEntity
    {
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// date of last execution
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime? DateRun { get; set; }
        /// <summary>
        /// the entity or subject on which execution took place
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string Entity { get; set; }
        /// <summary>
        /// flag determining if execution has finished
        /// </summary>
        public int? RunFlag { get; set; }
        /// <summary>
        /// the count during the execution
        /// </summary>
        public int? EntityCount { get; set; }
    }
}